openapi: 3.0.0
info:
  title: 6 Вариант, Порфирьев Антон
  description: Коллоквиум по КПО
  version: 0.0.1 alpha
servers:
  - url: http://localhost:2023
paths:
  /rates:
    get:
      summary: Возвращает список всех возможных курсов валют
      responses:
        '200':
          description: Список всех валют
          content:
            application/json:
              schema:
                type: object
              example:   # Sample object
                rates: [{"euro": 1, "ruble": 91.56}, {"ruble": 1, "euro": 0.010921799912625601}, {"dollar": 1, "ruble": 83.5}, {"ruble": 1, "dollar": 0.011976047904191617}, {"euro": 1, "dollar": 1.1}, {"dollar": 1, "euro": 0.9090909090909091}, {"zloty": 1, "dollar": 0.24}, {"dollar": 1, "zloty": 4.166666666666667}, {"zloty": 1, "ruble": 20.45}, {"ruble": 1, "zloty": 0.0488997555012225}]
  /exchange:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                currency_origin:
                  type: string
                currency_target:
                  type: string
                amount:
                  type: number
                  format: double
              required:
                - currency_origin
                - currency_target
                - amount
            example:
              currency_origin: 'dollar'
              currency_target: 'ruble'
              amount: 100
      summary: Переводит одну валюту в другую.
      responses:
        '200':
          description: Количество денег в новой валюте
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  target:
                    type: number
                    format: double
              example:
                status: 'success'
                message: 'Валюта успешно переведена'
                target: 8350.0
        '204':
          description: Такой обмен не производиться
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
              example:
                status: 'failed'
                message: 'Такого курса не существует'